---
- name: Nextcloud Setup iet-182
  hosts: all # there should be only one server
  become: true
  become_user: root
  roles:
  - role: prep_os
    vars: # lists variables you can set in the role (duplicaete of the role)

  # - mariadb
  # - redis
  # - php-fpm
  # - certbot
  # - nginx
  # - prep_ssmtp
  # - prep_nextcloud
  
