---
- name: Nextcloud Setup iet-182
  hosts: all # there should be only one server
  become: true
  become_user: root
  vars_files:
  - settings.yml
  - secrets.yml
  roles:
  - role: prep_os
  - role: mariadb
  - role: redis
  - role: php_fpm
  - role: certbot
  - role: nginx
  - role: nextcloud
  post_tasks:
    - name: We are ready
      debug:
        msg: 
          - "Your Nextcloud at https://{{ fqdn }} is ready."
          - "Login with user: {{ nc_admin }} and password: {{ nc_passwd }} "
          - "Environment:"
          - "  DB Name: {{ nc_db }}"
          - "  DB User: {{ nc_db_user }}" 
          - "  Webroot: /var/www/nextcloud"
          - "  PHP Version: {{ php_version }}"
          - "  PHP-FPM Socket: {{ php_fpm_sock }}"
          - "  Data Dir: {{ data_dir }}"
          - "  OS: {{ ansible_distribution }}"