---
- name: Nextcloud Setup iet-182
  hosts: all # there should be only one server
  become: true
  become_user: root
  roles:
  - role: prep_os
  - mariadb
  - redis
  - php_fpm
  - certbot
  # - nginx
  # - prep_ssmtp
  # - prep_nextcloud
  
