# Taken from https://github.com/ReinerNippes/nextcloud/blob/master/roles/nc_fail2ban/tasks/main.yml
---
- name: Fail2ban is installed
  apt:
    name: fail2ban
    autoremove: true
    state: latest
- name: Fail2ban is enabled and running
  systemd:
    name: fail2ban
    enabled: true
    state: restarted
- name: Fail2ban config is present
  copy:
    src: nextcloud.conf
    dest: /etc/fail2ban/filter.d/nextcloud.conf 
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
- name: Nextcloud jail is present
  template:
    src: nextcloud.local.j2
    dest: /etc/fail2ban/jail.d/nextcloud.local 
    owner: root
    group: root  
    mode: 0644
  notify: restart fail2ban